library('caret')

# read result file generated by python
data = read.csv('python_rf_result.csv')

# set boolean features as factors
data$click_bool <- as.factor(data$click_bool)
data$booking_bool <- as.factor(data$booking_bool)
data$predicted_click <- as.factor(data$predicted_click)
data$predicted_booking <- as.factor(data$predicted_booking)

# check click_bool prediction
confusionMatrix(data$click_bool,data$predicted_click, positive = "1")


# check booking_bool prediction
confusionMatrix(data$booking_bool,data$booking_bool, positive = "1")
